version: '3.4'

services:
  client:
    image: fomouksdevacr.azurecr.io/fomo-client:latest
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:6001
  api:
    image: fomouksdevacr.azurecr.io/fomo-api:latest
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 6001:6001 
    environment:
      - MONGO_URL=mongodb+srv://admin:admin@cluster0.xsplmq9.mongodb.net/?retryWrites=true&w=majority/fomo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules