name: Trigger fomo client ci

on:
  push:
    branches:
      ['main']
    paths:
    - 'client/**'
    - '.github/worflows/fomo-client-ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: fomouksdevacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push container image to registry
        run: |
          docker build "$GITHUB_WORKSPACE/client" -f "client/Dockerfile" -t fomouksdevacr.azurecr.io/fomo-client:${{ github.sha }}
          docker push fomouksdevacr.azurecr.io/fomo-client:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n fomo-client-uks-dev-aca -g fomo-uks-dev-rg --server fomouksdevacr.azurecr.io --username  ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
            az containerapp update -n fomo-client-uks-dev-aca -g fomo-uks-dev-rg --image fomouksdevacr.azurecr.io/fomo-client:${{ github.sha }}
